---
title: "HAT Monitoring Cover Data"
author: "Wendy Anthony for HAT"
date: "23/02/2026"
output:
  html_document:
    highlight: zenburn
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    # highlight: textmate
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '3'
# word_document:
  # mainfont: "Arial"      # Your main font (serif or sans-serif)
  # sansfont: "Helvetica"  # The specific sans-serif font for sans-serif contexts
  # fontsize: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prepare Cover Data to be imported into Webfilter

## Import Cover Data
```{r data-import-cover}
# Load Data
################################# 
# Cover data
cover_data <- read.csv("data/HAT_cover_mean.csv", fileEncoding="UTF-8")
```


### Explore Cover Data
```{r explore-cover-data}
str(cover_data)
```


## Import Species Count
```{r data-import-species-count}
# Load Data
################################# 
# Species counts
species_count <- read.csv("data/species_counts.csv", fileEncoding="UTF-8")

#############################################
# drop unknown species
species_count <- species_count[-c(25), ]
species_count <- species_count %>%
  rename(Site = Location)

write.csv(species_count, "data/species_count_wrangled.csv")
```








