---
title: "HAT Monitoring Site Data"
author: "Wendy Anthony for HAT"
date: "23/02/2026"
output:
  html_document:
    highlight: zenburn
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    # highlight: textmate
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Prepare Site Data to be imported into Webfilter
## Import site data
```{r data-import-site, include = FALSE}
# Load Data
################################# 
# Sites Data
HAT_sites_HAT <- read.csv("data/HAT-Sites-HAT.csv", fileEncoding="UTF-8")
str(HAT_sites_HAT)
head(HAT_sites_HAT)
colnames(HAT_sites_HAT)
```


## Rename Site Locationand columns
```{r rename-site-location-worksite-columns-for-sd-group, include = FALSE}
#############################################
# Sites Data
HAT_sites_HAT
colnames(HAT_sites_HAT)
HAT_sites_HAT$FullName <- HAT_sites_HAT$Site
HAT_sites_HAT$Site <- gsub("Matson Conservation Area", "Matson", HAT_sites_HAT$Site)
HAT_sites_HAT$Site <- gsub("Oak Haven Park", "Oak Haven", HAT_sites_HAT$Site)
HAT_sites_HAT$Site <- gsub("Havenwood Park", "Havenwood", HAT_sites_HAT$Site)

#############################################
# Round metrics values to 1 decimal
str(HAT_sites_HAT)
HAT_sites_HAT$Hours_per_Biomass_2022 <- sprintf("%.1f", HAT_sites_HAT$Hours_per_Biomass_2022)
HAT_sites_HAT$Hours_per_Biomass_2023 <- sprintf("%.1f", HAT_sites_HAT$Hours_per_Biomass_2023)
HAT_sites_HAT$Hours_per_Biomass_2024 <- sprintf("%.1f", HAT_sites_HAT$Hours_per_Biomass_2024)
HAT_sites_HAT$Hours_per_Biomass_2025 <- sprintf("%.1f", HAT_sites_HAT$Hours_per_Biomass_2025)
HAT_sites_HAT$Crew_Hours_2022 <- sprintf("%.1f", HAT_sites_HAT$Crew_Hours_2022)
HAT_sites_HAT$Crew_Hours_2023 <- sprintf("%.1f", HAT_sites_HAT$Crew_Hours_2023)
HAT_sites_HAT$Crew_Hours_2024 <- sprintf("%.1f", HAT_sites_HAT$Crew_Hours_2024)
HAT_sites_HAT$Crew_Hours_2025 <- sprintf("%.1f", HAT_sites_HAT$Crew_Hours_2025)
HAT_sites_HAT$Biomass_2022 <- sprintf("%.1f", HAT_sites_HAT$Biomass_2022)
HAT_sites_HAT$Biomass_2023 <- sprintf("%.1f", HAT_sites_HAT$Biomass_2023)
HAT_sites_HAT$Biomass_2024 <- sprintf("%.1f", HAT_sites_HAT$Biomass_2024)
HAT_sites_HAT$Biomass_2025 <- sprintf("%.1f", HAT_sites_HAT$Biomass_2025)
HAT_sites_HAT$Area_2022 <- sprintf("%.1f", HAT_sites_HAT$Area_2022)
HAT_sites_HAT$Area_2023 <- sprintf("%.1f", HAT_sites_HAT$Area_2023)
HAT_sites_HAT$Area_2024 <- sprintf("%.1f", HAT_sites_HAT$Area_2024)
HAT_sites_HAT$Area_2025 <- sprintf("%.1f", HAT_sites_HAT$Area_2025)
str(HAT_sites_HAT)
write.csv(HAT_sites_HAT, "data/HAT_sites_HAT_wrangled.csv")
```
